pipeline {
    agent any
    environment {
        DOCKER_USERNAME = credentials('DOCKER_USERNAME')
        DOCKER_PASSWORD = credentials('DOCKER_PASSWORD')
        install = "false"
        DATABASE_URI = credentials("DATABASE_URI")
    }
    stages {
        stage("Install requirements") {
            steps {
                script{
                    if (env.install == 'false'){
                        sh "bash jenkins/install-requirements.sh"
                    }
                }
            }
        }
        stage("Test") {
            steps {
                // pytest
                // each service run
                // make cov reports
                sh "bash jenkins/test.sh"
            }
        }
        stage("Build") {
            steps {
                // install docker and docker-compose
                // docker-compose build 
                sh "docker-compose build"
            }
        }
        stage("Push") {
            steps {
                // push docker-compose
                sh "docker-compose push"
            }
        }
        stage("Config Management (Ansible)") {
            steps {
                // installing ansible on the jenkins machine
                sh "bash jenkins/ansible.sh"
            }
        }
        stage("Deploy") {
            steps {
                // create swarm
                // copy docker-compose.yaml
                // docker stack deploy
                sh "bash jenkins/deploy.sh"
                // ansiblePlaybook credentialsId: 'ef6a5a50-0f0d-4586-8e54-a6d8084a9cde', installation: 'ansible1', inventory: 'ansible/inventory.yaml', playbook: 'ansible/playbook.yaml'
            }
        }
    }
}