---
# tasks file for nginx
- name: Install nginx
  apt: 
    pkg:
    - nginx
    update_cache: true
    state: latest

- name: Start nginx service
  service:
    name: nginx
    state: started

- name: Add nginx conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted